spring:
  datasource:
    url: 'jdbc:postgresql://dbserver:5432/knowledgebase'
    username: 'postgres'
    password: 'postgres'

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

debug: true

