spring:
  datasource:
    url: 'jdbc:postgresql://dbserver:5432/knowledgebase'
    username: 'postgres'
    password: 'postgres'
  flyway:
    locations: 'classpath:db/migration/{vendor}'

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
    com:
      cyber: TRACE

debug: true

